spring.application.name=studyhub
server.port=8080

spring.datasource.url=${env.DB_URL:jdbc:mysql://localhost:3306/studyhub?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${env.DB_USERNAME:sa}
spring.datasource.password=${env.DB_PASSWORD:123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

spring.mail.host=${env.MAIL_HOST:smtp.gmail.com}
spring.mail.port=${env.MAIL_PORT:587}
spring.mail.username=${env.MAIL_USERNAME:learnhub391@gmail.com}
spring.mail.password=${env.MAIL_PASSWORD:rivu yxgn hqkz uepl}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.base-url=${env.APP_BASE_URL:http://localhost:8080}
app.password-reset-expiry-minutes=30
